<a href="https://colab.research.google.com/github/bhlr/Ciencia-de-Datos-en-Python-Seccion-U.../blob/main/ejercicios6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejercicio: Investigar y ejemplificar diferencias entre np.array y np.matrix

* np.matrix : Returns a matrix from an array-like object, or from a string of data. A matrix is a specialized 2-D array that retains its 2-D nature through operations. It has certain special operators, such as * (matrix multiplication) and ** (matrix power). (It is no longer recommended to use this class, even for linear algebra. Instead use regular arrays. The class may be removed in the future.)

* np.array : numpy arrays (ndarrays) are N-dimensional.

Matrix tiene algunas ventajas en cuanto a calculos especialmente multiplicacion de matrices. 



In [3]:
import numpy as np

a = np.matrix('1 2; 3 4')
b = np.matrix('1 2; 3 4')
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )
A * B
print(a*b)

[[ 7 10]
 [15 22]]


# Ejercicio aplicado en DS Se tiene una red neuronal sencilla(y simplificada) como la de la siguiente imagen: 

<img src="https://www.oreilly.com/library/view/practical-convolutional-neural/9781788392303/assets/246151fb-7893-448d-b9bb-7a87b387a24b.png">

Donde:
* INPUT LAYER: un vector X de tamaño = 2 que representa los datos de entrada
* HIDDEN_LAYER :capa oculta con 2 neuronas definidas por los vectores:
    * HL1 = [0.25,0.37]
    * HL2 = [-8,14]
* OUTPUT_LAYER = capa de salida definida por el vector [4,9]

Crear una funcion neural_network(X) para calcular:
* Calcule la salida de cada neurona en la capa intermedia aplicada a la capa de entrada.
* Use el resultado del paso anterior como entrada para la neurona en la capa de salida

Utilizando multiplicación de matrices se debe calcular para cada fila de la matriz de entrada X el valor de las neuronas de la capa intermedia, esto producirá una nueva matriz con el mismo número de filas que X y 2 columnas(1 para cada neurona) , a  los valores de esta matriz se les debe aplicar la función "sigmoid"(descrita a continuación) para limitarlos al intervalo de 0 a 1, esto produce una matriz del mismo tamaño pero con valores entre 0 a 1, esta matriz se multiplica matricialmente por la matriz que representa los pesos de la capa de salida  y este proceso produce un nuevo tensor al cual se debe aplicar nuevamente la función sigmoid. El resultado debe ser un tensor con el mismo número de filas que la matriz X y una sola columna(una predicción para cada fila de X.

<img src="https://cdn-images-1.medium.com/max/1600/1*Xu7B5y9gp0iL5ooBj7LtWw.png">


In [7]:
def sigmoid(z): 
    return 1/(1+np.exp(-z))

def neural_network(X):
  HL = np.array([[0.25,-8],
                 [0.37,14]])
  OL = np.array([[4],[9]])
  
  NL = np.matmul(X,HL)
  NL = sigmoid(NL)
  ON = np.matmul(NL,OL)
  ON = sigmoid(ON)
  return ON

X =  np.array([[0.8,0.4],
               [2,3]])
 
neural_network(X)

array([[0.994146 ],
       [0.9999956]])

### Ejercicio 

Implementar en una funcion neural_network(X) la red neuronal definida por la siguiente arquitectura:

<img src="http://i.imgur.com/UNlffE1.png">

Podemos validar si fue correctamente implementada si usamos como entrada el vector x=[1,1] . Debemos obtener el resultado mostrado en la imagen.

Una vez tenemos la implementacion correcta, cambiar la funcion de activacion de la capa de salida por la funcion de activacion ReLu(https://en.wikipedia.org/wiki/Rectifier_(neural_networks)):

<img src="https://cdn-images-1.medium.com/max/1600/1*DfMRHwxY1gyyDmrIAd-gjQ.png">

Luego evaluar la red neuronal sobre la matriz de datos X(de manera vectorizada):

In [27]:
def sigmoid(z): 
    return 1/(1+np.exp(-z))

def neural_network(X):
  HL = np.array([[0.82,0.69],
                 [1.21,0.77],
                 [0.74,0.68]])
  HL = np.array([[0.82,1.21,0.74],
                 [0.69,0.77,0.68]])
  OL = np.array([[0.116],[0.329],[0.708]])
  NL = np.matmul(X,HL)
  print(NL)
  NL = sigmoid(NL)
  ON = np.matmul(NL,OL)
  ON = sigmoid(ON)
  return ON

#X =  np.array([[0.8,0.4],[2,3]])
X= np.array([[1,1,1],[1,1,1],[1,1,1]])
X= np.array([1,1])
neural_network(X)

[1.51 1.98 1.42]


array([0.72197446])